### ISSUE TITLE
Feat: Add links to popular `Big Tech` Style Guides

### ISSUE THREAD

**Issue by nelsonic** [dwyl/style-guide#35]
+ https://developers.google.com/style
+ https://support.apple.com/en-gb/guide/applestyleguide
+. https://learn.microsoft.com/en-us/style-guide
+ https://developers.cloudflare.com/style-guide/
+ https://buffer.com/resources/style-guide/
also:
+ https://en.wikipedia.org/wiki/List_of_style_guides

# Todo

+ [ ] Do 5-10 mins of research for other **`Big Tech`** (but not [`Meta`](https://github.com/dwyl/learn-react/issues/23#issuecomment-1778577937)) Style Guides. 
  + [ ] Leave comments with links in this thread. 💬 
+ [ ] Create a Pull Request adding the section "Links to Popular Style Guides" and bullet points with links.
